# -*- coding: utf-8 -*-
"""ITE Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wwrV5cV3NzFEKJh6YKWa8KlPg0ZiN86s
"""

import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv(r'/content/drive/MyDrive/Collab Notebook/googleplaystore.csv')

data.head(5)

data.tail(5)

data.columns

data.describe()

data.hist()

#check how many rating are more than 5 outlier
data[data.Rating > 5]

"""1. Displaying top 5 apps with highest review"""

data.iloc[index]['App']

"""  2.Which Category Getting The Hightest Average Rating?

"""

data.groupby('Category')['Rating'].mean().sort_values(ascending=False)

"""3. Find the total number which have 5 Star rating

"""

len(data[data['Rating']==5.0])

"""4. Find the average rating of free and paid apps."""

data.groupby('Type')['Rating'].mean()